### ISSUE TITLE
Email id as username doesn't work

### ISSUE THREAD

**Issue by palaniraja** [org-trello/org-trello.github.io#49]
Thank you for this package. 👍 

After a lot of struggle i figured that if you use trello userid (could be a email) then sync doesn't work throws the consumer-key/access-token issue, thought the `.trello/~userid.el` is populated with valid key and token.

**Comment by ardumont** [comment]
Hello, 

> Thank you for this package. :+1:

Thanks.

Can you please report back those issues in https://github.com/org-trello/org-trello/issues?

Thanks in advance.

Cheers,

**Comment by palaniraja** [comment]
Created https://github.com/org-trello/org-trello/issues/359
