### ISSUE TITLE
Trello->Emacs sync comment not working

### ISSUE THREAD

**Issue by palaniraja** [org-trello/org-trello.github.io#50]
Also, I found that the card comment from trello->emacs (C-u org-trello-sync-comment) doesn't work but show `org-trello No comment to delete - skip` message

**Comment by ardumont** [comment]
Hello, can you please report back those issues in https://github.com/org-trello/org-trello/issues?
(also, if you could close this one here, thanks).

Thanks in advance.

Cheers,

**Comment by palaniraja** [comment]
Closing this issue, to be followed up on https://github.com/org-trello/org-trello/issues/360
